backend:
    name: git-gateway
    branch: main

local_backend: true

media_folder: '/assets/uploads'
public_folder: '_site/assets/uploads'

collections:
    - name: 'projects'
      label: 'Projects'
      folder: 'src/projects'
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      create: true
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'project' }
          - { label: 'Project Title', name: 'title', widget: 'string' }
          - { label: 'Project Description', name: 'description', widget: 'string' }
          - { label: 'Hero Image', name: 'heroImage', widget: 'image' }
          - label: 'Other Images'
            name: 'otherImages'
            widget: 'list'
            fields:
                - { label: 'Image', name: 'image', widget: 'image' }
                - { label: 'Name', name: 'name', widget: 'string' }
          - label: 'Tags - Type of Project'
            name: 'tagsType'
            widget: 'select'
            multiple: true
            options:
                - { label: 'Logo', value: 'logo' }
                - { label: 'Brochure', value: 'brochure' }
                - { label: 'Rebrand', value: 'rebrand' }
                - { label: 'Restaurant Menu', value: 'menu' }
          - label: 'Tags - Project Aesthetic/Style'
            name: 'tagsAesthetic'
            widget: 'select'
            multiple: true
            options:
                - { label: 'Retro', value: 'retro' }
                - { label: 'Corporate', value: 'corporate' }
                - { label: 'French Chic', value: 'frenchChic' }
          - { label: 'Is this a hero project (displayed on the home page)?', name: 'heroProject', widget: 'boolean' }
