# This was the original config file before building it dynamically. For reference on how things should look in case it ever outputs incorrectly
backend:
    name: git-gateway
    branch: main

local_backend: true

media_folder: '/assets/uploads'
public_folder: '/assets/uploads'

collections:
    - name: 'projects'
      label: 'Projects'
      folder: 'src/projects'
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      create: true
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'project' }
          - { label: 'Project Title', name: 'title', widget: 'string' }
          - { label: 'Project Description', name: 'description', widget: 'string' }
          - {
                label: "Display this project with it's category tile on the home page?",
                name: 'heroProject',
                widget: 'boolean',
            }
          - label: 'Categories'
            name: 'categories'
            widget: 'select'
            multiple: true
            options:
                - { label: 'Logo & Branding', value: 'logoBranding' }
                - { label: 'Product Design & Layout', value: 'productDesignLayout' }
                - { label: 'Illustration', value: 'illustration' }
                - { label: 'Business Cards', value: 'businessCards' }
                - { label: 'Menu', value: 'menu' }
                - { label: 'Gift Cards', value: 'giftCards' }
          - { label: 'Hero Image', name: 'heroImage', widget: 'image' }
            # widget: 'object'
            # fields:
            #     - { label: 'Image', name: 'image', widget: 'image' }
            #     - { label: 'Image Description', name: 'description', widget: 'string' }
          - label: 'Other Images'
            name: 'otherImages'
            widget: 'list'
            fields:
                - { label: 'Image', name: 'image', widget: 'image' }
                - { label: 'Image Description', name: 'description', widget: 'string' }
