backend:
    name: git-gateway
    branch: main

local_backend: true

media_folder: '_site/assets/uploads'
public_folder: '/assets/uploads'

collections:
    - name: 'projects'
      label: 'Projects'
      folder: 'src/projects'
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      create: true
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'project' }
          - { label: 'Project Title', name: 'title', widget: 'string' }
          - { label: 'Project Description', name: 'description', widget: 'string' }
          - { label: 'Hero Image', name: 'heroImage', widget: 'image' }
          - label: 'Other Images'
            name: 'otherImages'
            widget: 'list'
            fields:
                - { label: 'Image', name: 'image', widget: 'image' }
                - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'Is this a hero project (displayed on home page)?', name: 'heroProject', widget: 'boolean' }
